services:
  inference-server-cpu:
    build:
      context: .
      args:
        CPU_OR_GPU: cpu
    ports:
      - "8090:8080"
    environment:
      ADDRESS: 0.0.0.0
      PORT: 8080
      MODELS_ROOT: /usr/models
    volumes:
      - "${MODELS_ROOT_HOST}:/usr/models"