services:
  inference-server-cpu:
    environment:
      PORT: 5002
    extends:
      file: AiDetector/inference-server/compose.cpu.yaml
      service: inference-server-cpu
    ports:
      - "5002:5002"
  db:
    environment:
      PGPORT: 5001
    extends:
      service: db
      file: detector/compose.base.yml
    ports:
      - "5001:5001"

volumes:
  dbVolume:
    driver: local