import numpy as np
import pandas as pd
from sklearn.cluster import KMeans


# Following file is generated by Gemini for faster prototyping!


def calculate_gap_statistic(data, n_refs=10, max_k=10):
    """
    Calculates the Gap Statistic to determine the optimal number of clusters.

    Args:
        data (np.array): Input data matrix (n_samples, n_features).
        n_refs (int): Number of random reference datasets to generate.
        max_k (int): Maximum number of clusters to test.

    Returns:
        pd.DataFrame: DataFrame containing Gap values and criteria for each k.
    """
    shape = data.shape

    # Range of k to test
    ks = range(1, max_k + 1)

    # 1. Dispersion for Real Data
    # WCSS (Inertia) for original data
    wcss_orig = np.zeros(len(ks))

    for i, k in enumerate(ks):
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit(data)
        wcss_orig[i] = kmeans.inertia_

    # 2. & 3. Dispersion for Reference Data
    # We store log(WCSS) directly
    val_ref = np.zeros((len(ks), n_refs))

    # Create reference datasets (uniform distribution within data bounds)
    # Using a bounding box approach
    mins = np.min(data, axis=0)
    maxs = np.max(data, axis=0)

    for b in range(n_refs):
        # Generate random matrix
        random_data = np.random.uniform(mins, maxs, shape)

        for i, k in enumerate(ks):
            kmeans_ref = KMeans(n_clusters=k, n_init=10)
            kmeans_ref.fit(random_data)
            val_ref[i, b] = kmeans_ref.inertia_

    # 4. Calculate Gap
    # Mean of log(WCSS) for reference data
    log_wcss_ref_mean = np.mean(np.log(val_ref), axis=1)
    log_wcss_orig = np.log(wcss_orig)

    gap_values = log_wcss_ref_mean - log_wcss_orig

    # 5. Standard Deviation & Simulation Error (sk)
    # Standard deviation of the log(WCSS) across references
    sd_k = np.std(np.log(val_ref), axis=1)
    sk = sd_k * np.sqrt(1 + 1 / n_refs)

    # Create results DataFrame
    df = pd.DataFrame(
        {
            "k": ks,
            "gap": gap_values,
            "sk": sk,
            "gap_k+1": np.append(gap_values[1:], np.nan),  # Shifted for comparison
            "sk_k+1": np.append(sk[1:], np.nan),  # Shifted for comparison
        }
    )

    # Calculate Tibshirani's criterion: Gap(k) >= Gap(k+1) - s(k+1)
    df["diff"] = df["gap"] - (df["gap_k+1"] - df["sk_k+1"])

    return df


def get_optimal_k_programmatically(gap_df):
    """
    Determines optimal k using Tibshirani's 1-standard-error rule.

    Args:
        gap_df (pd.DataFrame): The output from calculate_gap_statistic()
                               Must contain columns: 'gap', 'gap_k+1', 'sk_k+1'

    Returns:
        dict: {'optimal_k': int, 'is_clusterable': bool, 'method': str}
    """
    # Tibshirani's Rule:
    # Choose smallest k where Gap(k) >= Gap(k+1) - s(k+1)
    # We essentially look for where the 'diff' becomes positive
    # (assuming diff was calculated as: gap - (gap_next - sk_next))

    # Filter for rows where the rule is met
    candidates = gap_df[gap_df["diff"] >= 0]

    if not candidates.empty:
        # The first k that satisfies the condition is the optimal one
        optimal_k = int(candidates.iloc[0]["k"])
        reason = "1-Standard-Error Rule (First k satisfying Tibshirani's criterion)"
    else:
        # Fallback: If the rule is never strictly met (rare),
        # usually implies the Gap keeps increasing.
        # We pick the k with the absolute Maximum Gap.
        optimal_k = int(gap_df.loc[gap_df["gap"].idxmax()]["k"])
        reason = "Max Gap Value (Tibshirani's rule not met within range)"

    # Determine Clusterability
    is_clusterable = optimal_k > 1

    return {"optimal_k": optimal_k, "is_clusterable": is_clusterable, "reason": reason}
