name: Java CI with Maven

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  M2_CACHE_KEY: m2_cache

jobs:
  build-and-publish-maven:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Calculate Version
        run: |
          chmod +x .github/scripts/calculate-version.sh
          .github/scripts/calculate-version.sh

      - name: Run integration tests
        working-directory: ./build-plugins
        run: ../mvnw --batch-mode verify

      - name: Install to Maven local
        working-directory: ./build-plugins
        run: ../mvnw --batch-mode install
      
      - name: Publish jena-plugin-core & jena-maven-plugin
        if: startsWith(github.ref, 'refs/tag/v')
        working-directory: ./build-plugins
        run: |
          ../mvnw --batch-mode versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false
          ../mvnw --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven local
        id: cache
        uses: actions/cache@v5.0.2
        with:
          path: ~/.m2
          key: ${{ env.M2_CACHE_KEY }}
        

  build-and-publish-gradle:
    needs: build-and-publish-maven
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Restore Cache Maven local
        id: restore-cache
        uses: actions/cache@v5.0.2
        with:
          key: ${{ env.M2_CACHE_KEY }}

      - name: Calculate Version
        run: |
          chmod +x .github/scripts/calculate-version.sh
          .github/scripts/calculate-version.sh

      - name: Setup Gradle Wrapper
        working-directory: ./build-plugins/jena-gradle-plugin
        run: chmod +x ./gradlew

      - name: Run tests
        working-directory: ./build-plugins/jena-gradle-plugin
        run: ./gradlew test -Pversion=${{ env.VERSION }} --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish jena-gradle-plugin
        if: startsWith(github.ref, 'refs/tag/v')
        working-directory: ./build-plugins/jena-gradle-plugin
        run: |
          ./gradlew publish -x test -Pversion=${{ env.VERSION }} --no-daemon
          ./gradlew publishToMavenLocal -x test -Pversion=${{ env.VERSION }} --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-jena:
    needs:
      - build-and-publish-maven
      - build-and-publish-gradle
    permissions:
      checks: write
      contents: write

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Calculate Version
      run: |
        chmod +x .github/scripts/calculate-version.sh
        .github/scripts/calculate-version.sh

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Restore Cache Maven local
      id: restore-cache
      uses: actions/cache@v5.0.2
      with:
        key: ${{ env.M2_CACHE_KEY }}

    - name: Setup wrapper
      run: chmod +x mvnw

    - name: Set Versions of project
      run: ./mvnw --batch-mode versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false

    - name: Build Maven projects
      run: ./mvnw -B package --file pom.xml -DskipTests

    - name: Run unit tests
      working-directory: ./detector
      run: ../mvnw --batch-mode test

    - name: Run integration tests
      working-directory: ./detector
      run: ../mvnw --batch-mode verify -DskipUnitTests

    - name: Publish surefire results
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'

    - name: Publish failsafe results
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: '**/target/failsafe-reports/TEST-*.xml'

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        ignore-maven-wrapper: 'true'
