name: Python AiDetector Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  training-project:
    uses: ./.github/workflows/python-workflow.yml
    with:
      project_path: ./AiDetector/training
      RUN_UNITTEST:
      python_version: 3.13
      poetry_version: 2.2.1