name: python-workflow.yml
on:
  workflow_call:
    inputs:
      poetry_version:
        type: string
        required: true
      python_version:
        type: string
        required: true
      project_path:
        type: string
        required: true



jobs:
  training-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Install dependencies
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: |
          poetry install --with dev
      - name: Run tests using unittest
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: poetry run python -m unittest discover -s tests -p 'test_*.py' -v
      - name: Check formatting
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: poetry run ruff format --check
      - name: Running linter
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: poetry run ruff check