name: Python AiDetector Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ADDRESS: 0.0.0.0
  PORT: 8080
  PROJECT_PATH: ./AiDetector/inference-server
  MODELS_ROOT: ${{ env.PROJECT_PATH }}/tests/resources/model_root

jobs:
  training-project:
    uses: ./.github/workflows/python-workflow.yml
    with:
      project_path: ./AiDetector/training
      python_version: 3.13
      poetry_version: 2.2.1

  inference-server:
    uses: ./.github/workflows/python-workflow.yml
    with:
      project_path: ${{ env.PROJECT_PATH }}
      python_version: 3.13
      poetry_version: 2.2.1
      post_setup_script: source scripts/generate-server.sh