name: Python AiDetector Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TRAINING_PROJECT_PATH: ./AiDetector/training
  RUN_UNITTEST: poetry run python -m unittest discover -s tests -p 'test_*.py' -v
  PYTHON_VERSION: 3.13
  POETRY_VERSION: 2.2.1

jobs:
  training-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Install dependencies
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: |
          poetry install --with dev
      - name: Run tests using unittest
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: ${{ env.RUN_UNITTEST }}
      - name: Check formatting
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: poetry run ruff format --check
      - name: Running linter
        working-directory: ${{ env.TRAINING_PROJECT_PATH }}
        run: poetry run ruff check
