spring:
  datasource:
    username: root
    password: detector
    url: jdbc:postgresql://localhost:5431/antipatternDetector
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  grpc:
    client:
      channels:
        inference-server:
          address: localhost:8081

inference:
  enabled: true
  models:
    - &comments-model
      model-name: comments-model
      batch-size: 30
      batch-period: 100
    - &god-di-model
      model-name: god-di-model
      batch-size: 30
      batch-period: 100

  detectors:
  - detector-name: technical-debt
    extractor: comments
    model: *comments-model
    evaluations:
      - label-name: "technical_debt"
        threshold: 0.8
        issue-type: SELF_ADMITTED_TECHNICAL_DEBT
      - label-name: "code_comment"
        threshold: 0.8
        issue-type: COMMENTED_OUT_CODE

  - detector-name: god-di
    extractor: god-metrics
    model: *god-di-model
    evaluations:
      - label-name: "god_di"
        threshold: 1
        issue-type: GOD_DI_CLASS

prepare-plugin:
  artifact:
    group-id: "cz.muni.fi.jena"
    artifact-id: "jena-maven-plugin"
#    version: @project.version@
    version: 0.0.0-PR25-248d05c
  repository:
    id: jena-github
    # Repository pull token
    url: https://x-access-token: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@maven.pkg.github.com/Ricaps/JenaV3
