spring:
  datasource:
    username: root
    password: detector
    url: jdbc:postgresql://localhost:5431/antipatternDetector
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  grpc:
    client:
      channels:
        inference-server:
          address: localhost:8080

inference:
  enabled: true
  detectors:
  - detector-name: technical-debt
    extractor: comments
    model-name: comments-model
    issue-type: SELF_ADMITTED_TECHNICAL_DEBT
    label:
      label-name: "technical_debt"
      threshold: 0.90

  - detector-name: code-comments
    extractor: comments
    model-name: comments-model
    issue-type: COMMENTED_OUT_CODE
    label:
      label-name: "code_comments"
      threshold: 0.90

